services:
  - type: web
    name: msml605-backend
    runtime: docker
    branch: amey-demo
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /api/status