from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd


logger = logging.getLogger(__name__)

BASELINE_LABEL_PREFIX = "Without"
TUNED_LABEL_PREFIX = "With MLflow"


def _fmt_seconds(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "N/A"
    if value < 60:
        return f"{value:.1f}s"
    return f"{value / 60.0:.2f}m"


def _fmt_metric(value: float | None) -> str:
    return f"{value:.4f}" if pd.notna(value) else "N/A"


def _fmt_percent(value: float | None) -> str:
    return f"{value:.2f}%" if pd.notna(value) else "N/A"


def _df_to_markdown(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub-flavored markdown table.

    Prefers pandas.to_markdown (tabulate), falls back to a hand-rolled renderer
    so the report works without the optional tabulate dependency.
    """
    try:
        return df.to_markdown(index=False)
    except ImportError:
        headers = [str(c) for c in df.columns]
        lines = ["| " + " | ".join(headers) + " |"]
        lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
        for _, row in df.iterrows():
            cells = ["" if pd.isna(v) else str(v) for v in row.tolist()]
            lines.append("| " + " | ".join(cells) + " |")
        return "\n".join(lines)


def generate_tuning_report(
    df_comp: pd.DataFrame,
    target_file: str = "MLOPS_PERFORMANCE_REPORT.md",
) -> None:
    report_path = Path(target_file)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    render_df = df_comp.copy()
    if "Time To Target Seconds" in render_df.columns:
        render_df["Time To Target"] = render_df["Time To Target Seconds"].apply(_fmt_seconds)
    if "Best Metric" in render_df.columns:
        render_df["Best Metric"] = render_df["Best Metric"].apply(_fmt_metric)
    if "Percent Time Saved" in render_df.columns:
        render_df["Percent Time Saved"] = render_df["Percent Time Saved"].apply(_fmt_percent)

    preferred_cols = [
        "Workflow",
        "Experiment",
        "Metric Name",
        "Target Threshold",
        "Reached Target",
        "Runs Needed",
        "Best Metric",
        "Time To Target",
        "Absolute Time Saved Seconds",
        "Percent Time Saved",
    ]
    output_cols = [c for c in preferred_cols if c in render_df.columns]

    with report_path.open("w", encoding="utf-8") as f:
        f.write("# MLOps Hyperparameter Tuning - Time-to-Target Report\n\n")
        f.write(
            "This report compares **without-MLflow tuning workflow** vs "
            "**MLflow-based tuning workflow** on how fast each reaches the same target metric.\n\n"
        )
        f.write(_df_to_markdown(render_df[output_cols]))
        f.write("\n\n")

        conclusion = _build_conclusion(df_comp)
        f.write(conclusion)

    logger.info("Generated report: %s", report_path)


def _build_conclusion(df_comp: pd.DataFrame) -> str:
    workflow = df_comp.get("Workflow")
    if workflow is None:
        return "**Conclusion:** No workflow data available.\n"

    baseline_mask = workflow.str.startswith(BASELINE_LABEL_PREFIX, na=False)
    tuned_mask = workflow.str.startswith(TUNED_LABEL_PREFIX, na=False)
    baseline_row = df_comp[baseline_mask]
    tuned_row = df_comp[tuned_mask]

    if baseline_row.empty or tuned_row.empty:
        return "**Conclusion:** Baseline or tuned workflow row missing from input.\n"

    baseline_time = baseline_row.iloc[0].get("Time To Target Seconds")
    tuned_time = tuned_row.iloc[0].get("Time To Target Seconds")
    if not (pd.notna(baseline_time) and pd.notna(tuned_time)):
        return (
            "**Conclusion:** At least one workflow has not yet reached the target "
            "threshold in the selected experiment history.\n"
        )

    saved_seconds = float(baseline_time) - float(tuned_time)
    saved_pct = (saved_seconds / float(baseline_time) * 100.0) if baseline_time > 0 else 0.0
    return (
        f"**Conclusion:** MLflow-based tuning saved `{saved_seconds:.1f}` seconds "
        f"({saved_pct:.2f}%) to reach the same performance target.\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate markdown report from time-to-target CSV."
    )
    parser.add_argument(
        "--input-csv",
        default="metrics_improvements/time_to_target_comparison.csv",
        help="CSV generated by mlflow_metrics_comparison.py",
    )
    parser.add_argument(
        "--output-md",
        default="MLOPS_PERFORMANCE_REPORT.md",
        help="Output markdown report path",
    )
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    args = parse_args()
    df_comp = pd.read_csv(args.input_csv)
    generate_tuning_report(df_comp=df_comp, target_file=args.output_md)


if __name__ == "__main__":
    main()
